config/routes.rb
Rails.application.routes.draw do
  root "shift_offers#index"
  resources :locations
  resources :associates, only: [:index]
  resources :collaborators

  resources :skills, only: [:index]
  resources :certifications
  resources :jobs
  resources :shifts
  devise_for :admins
  devise_for :associates

  resources :shift_offers, only: [:index] do
    resources :schedules, only: [:create, :destroy], default: { format: :json }
  end
end

app/models/certification.rb
# == Schema Information
#
# Table name: certifications
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Certification < ApplicationRecord
  has_many :skills, inverse_of: :certification
  has_many :associates, through: :skills, inverse_of: :certifications
  has_and_belongs_to_many :certifications
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  before_action :set_certification, only: [:show, :edit, :update, :destroy]

  # GET /certifications
  # GET /certifications.json
  def index
    @certifications = Certification.all
  end

  # GET /certifications/1
  # GET /certifications/1.json
  def show
  end

  # GET /certifications/new
  def new
    @certification = Certification.new
  end

  # GET /certifications/1/edit
  def edit
  end

  # POST /certifications
  # POST /certifications.json
  def create
    @certification = Certification.new(certification_params)

    respond_to do |format|
      if @certification.save
        format.html { redirect_to @certification, notice: 'Certification was successfully created.' }
        format.json { render :show, status: :created, location: @certification }
      else
        format.html { render :new }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certifications/1
  # PATCH/PUT /certifications/1.json
  def update
    respond_to do |format|
      if @certification.update(certification_params)
        format.html { redirect_to @certification, notice: 'Certification was successfully updated.' }
        format.json { render :show, status: :ok, location: @certification }
      else
        format.html { render :edit }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certifications/1
  # DELETE /certifications/1.json
  def destroy
    @certification.destroy
    respond_to do |format|
      format.html { redirect_to certifications_url, notice: 'Certification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certification
      @certification = Certification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certification_params
      params.require(:certification).permit(:name)
    end
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/views/certifications/_form.html.erb
<%= form_with(model: certification, local: true) do |form| %>
  <% if certification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(certification.errors.count, "error") %> prohibited this certification from being saved:</h2>

      <ul>
      <% certification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/certifications/edit.html.erb
<h3>Certificación</h3>

<%= render 'form', certification: @certification %>

<%= link_to 'Show', @certification %> |
<%= link_to 'Back', certifications_path %>

app/views/certifications/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Certificaciones</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @certifications.each do |certification| %>
      <tr>
        <td><%= certification.name %></td>
        <td><%= link_to 'Show', certification %></td>
        <td><%= link_to 'Edit', edit_certification_path(certification) %></td>
        <td><%= link_to 'Destroy', certification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Certification', new_certification_path %>

app/views/certifications/new.html.erb
<h3>Nueva certificación</h3>

<%= render 'form', certification: @certification %>

<%= link_to 'Back', certifications_path %>

app/views/certifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @certification.name %>
</p>

<%= link_to 'Edit', edit_certification_path(@certification) %> |
<%= link_to 'Back', certifications_path %>